site_name: KNULLI Wiki
site_url: https://knulli.org
repo_url: https://github.com/knulli-cfw/knulli.org
repo_name: knulli.org
copyright: Copyright Creative Commons Attribution-ShareAlike 4.0 International
theme:
  name: material
  logo: _inc/images/logo-knulli.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: art-book
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: art-book-next
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Oxygen
    code: Oxygen Mono
  features:
    - navigation.top
    #- navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.follow 
    - search.suggest
    - content.tooltips
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
      permalink: ¶
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
extra_css:
  - _inc/css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/knulli-cfw/distribution
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/HXPS3DAeeB
  extra:
    alternate:
      - name: English
        link: /en/ 
        lang: en
      - name: Español
        link: /es/
        lang: es
      - name: Deutsch
        link: /de/
        lang: de
      - name: Polski
        link: /pl/
        lang: pl
      - name: Türkçe
        link: /tr/
        lang: tr
      - name: Português do Brasil
        link: /pt-BR/
        lang: pt-BR
plugins:
  - search:
      lang: [en, es, de, pl, tr, pt-BR]
  - glightbox
  - macros:
      include_dir: includes
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "KNULLI Wiki"
        - locale: es
          name: Español
          build: true
          site_name: "KNULLI Wiki"
          nav_translations:
            Home: Inicio
            FAQs: Preguntas Frecuentes 
            Play: Jugar
            Systems: Sistemas
            Devices: Dispositivos
            Install: Instalar
            Update: Actualizar
            Add Games: Añadir Juegos
            Achievements: Logros
            Controls: Controles
            Netplay: Juego en Red
            Unbranded: Sin Marca
        - locale: de
          name: Deutsch
          build: true
          site_name: "KNULLI Wiki"
          nav_translations:
            Home: Start
            FAQs: Häufige Fragen
            About KNULLI: Über KNULLI
            Troubleshooting: Problemlösungen
            Play: Spielen
            Devices: Geräte
            Install: Installation
            Update: Aktualisieren
            Add Games: Spiele hinzufügen
            Game Storage: Speicherort für Spiele
            Network Transfer: Netzwerkübertragung
            Accessing SD Card: Zugriff auf SD-Karte
            Second SD Card: Zweite SD-Karte
            Formatting: Formatieren
            Scraping: Scraping
            Hotkey shortcuts: Tastenkombinationen
            Achievements: Achievements
            Controls: Controller
            Configure: Konfiguration
            Networking: Netzwerkverbindungen
            Unbranded: Ohne Marke
            Bezel Decorations: Bezel-Dekorationen
        - locale: pl
          name: Polski
          build: true
          site_name: "KNULLI Wiki"
          nav_translations:
            Home: Strona główna
            FAQs: Często zadawane pytania
            Play: Graj
            Devices: Urządzenia
            Install: Instalacja
            Update: Aktualizacja
            Add Games: Dodaj gry
            Achievements: Osiągnięcia
            Controls: Sterowanie
            Unbranded: Bez marki
        - locale: tr
          name: Türkçe
          build: true
          site_name: "KNULLI Viki"
          nav_translations:
            Home: Anasayfa
            FAQs: Sıkça Sorulan Sorular 
            Play: Oyna
            Devices: Cihazlar
            Install: Kurulum
            Update: Güncelleme
            Add Games: Oyun Ekleme
            Achievements: Başarımlar
            Controls: Kontroller
            Netplay: Ağ Oyunu Desteği
            Unbranded: Markasız
        - locale: pt_BR
          name: Português do Brasil
          build: true
          site_name: "KNULLI Wiki"
          nav_translations:
            Home: Início
            FAQs: Perguntas Frequentes
            About KNULLI: Sobre o KNULLI
            Troubleshooting: Solução de Problemas
            Play: Jogar
            Quick Start Guide: Guia rápido
            Install: Instalação
            Add Games: Adicionar Jogos
            Game Storage: Armazenamento dos Jogos
            Network Transfer: Transferência via Rede
            Accessing SD Card: Acessando o Cartão SD
            Second SD Card: Segundo Cartão SD
            Formatting: Formatando
            Hotkey Shortcuts: Atalhos
            Achievements: Conquistas
            Update: Atualizar
            Configure: Configuração
            Networking: Rede
            Controls: Controles
            Collections: Coleções
            Bezel Decorations: Molduras
            Themes: Temas
            Systems: Sistemas
            Devices: Dispositivos
            Unbranded: Sem Marca
nav:
    - Home: index.md
    - FAQs:
      - FAQs: faq/index.md
      - About KNULLI: faq/knulli.md
      - Troubleshooting: faq/troubleshooting.md
    - Play:
      - Quick Start Guide: play/quick-start.md
      - Install: play/install.md
      - Add Games:
        - Add Games: play/add-games/index.md
        - Game Storage: play/add-games/game-storage.md
        - Network Transfer: play/add-games/network-transfer.md
        - Accessing SD Card: play/add-games/accessing-ext4.md
        - Second SD Card: play/add-games/second-sd-card.md
        - Formatting: play/add-games/formatting.md
      - Scraping: play/scraping.md
      - Hotkey Shortcuts: play/hotkey-shortcuts.md
      - Achievements: play/retro-achievements.md
      - Netplay: play/netplay.md
      - Update: play/update.md
    - Configure:
      - Networking: configure/networking.md
      - Controls: configure/controls.md
      - Collections: configure/collections.md
      - Bezel Decorations: configure/bezel-decorations.md
      - Themes: configure/themes.md
      - SSH: configure/ssh.md
      - Retroarch:
        - Controls: configure/retroarch/controls.md
      - PPSSPP:
        - Cheats: configure/ppsspp/cheats.md
    - Systems:
      - Engines:
        - Pico-8: systems/pico-8.md
      - PortMaster: systems/portmaster.md
    - Devices: 
      - devices/index.md
      - Anbernic:
        - RG35xx Original: devices/anbernic/rg35xx.md
        - RG35xx Plus: devices/anbernic/rg35xx-plus.md
        - RG35xx H: devices/anbernic/rg35xx-h.md
        - RG35xx 2024: devices/anbernic/rg35xx-2024.md
        - RG35xx SP: devices/anbernic/rg35xx-sp.md
      - Capcom:
        - Retro Station Tron: devices/capcom/retro-station-tron.md
      - Orange Pi Zero 2w:
        - Orange Pi Zero 2w: devices/orange-pi/orange-pi-zero-2w.md
      - Powkiddy:
        - Powkiddy A12: devices/powkiddy/rgb10-max-3-pro.md
        - Powkiddy A13: devices/powkiddy/rgb10-max-3.md
        - RGB30: devices/powkiddy/rgb30.md
        - X51: devices/powkiddy/x51.md
      - Sega:
        - Astro City Mini: devices/sega/astro-city-mini.md
      - SGJAM:
        - M17: devices/sgjam/m17.md
      - Taito:
        - Egret II Mini: devices/taito/egret-ii-mini.md
      - TrimUI:
        - TrimUI Smart Pro: devices/trimui/smart-pro.md
      - Unbranded:
        - PS5000: devices/unbranded/ps5000.md
        - PS7000: devices/unbranded/ps7000.md
        - PocketGo S30: devices/unbranded/pocketgo-s30.md
      - Unico:
        - Neo Geo Mini: devices/unico/neogeomini.md
        - MVSX: devices/unico/mvsx.md
        - Fun R1: devices/unico/fun-r1.md
        - Arcade Stick Pro: devices/unico/arcade-stick-pro.md
